import type { Artwork, Artist } from "./types"

export const artistData: Artist = {
  name: "공경순 (Kong Kyung Soon)",
  bio: "서울에서 활동하는 현대 서예가입니다. 전통 서예의 정신을 계승하면서도 현대적인 미감을 탐구하며, 문자의 조형성과 먹의 물성을 통해 내면의 세계를 표현합니다. 다수의 개인전과 그룹전에 참여하였으며, 그의 작품은 여러 미술관과 개인 컬렉션에 소장되어 있습니다.",
  statement:
    "나의 작업은 선과 공간, 여백의 관계를 탐구하는 과정입니다. 각 획은 순간의 호흡이며, 전체 구성은 우주적 질서와 조응하고자 하는 염원을 담고 있습니다. 전통에 뿌리를 두되, 동시대의 감성과 소통하는 새로운 서예의 가능성을 모색합니다.",
  profileImageUrl: "/Images/Artist/Artist.png",
}

export const artworksData: Artwork[] = [
  // 2025년 작품
  {
    id: "25",
    slug: "journey",
    title: "여행 (Journey)",
    year: 2025,
    medium: "화선지에 먹 (Ink on Mulberry Paper)",
    dimensions: "70 x 140 cm",
    aspectRatio: "1/2",
    description: "인생의 여행길에서 마주하는 다양한 풍경과 감정을 담은 작품입니다.",
    imageUrl: "/Images/Artworks/2025/heelang-journey-2025.jpg",
    imageUrlQuery: "journey calligraphy life path",
    artistNote: "길 위에서 느끼는 모든 순간들이 하나의 작품으로 완성되었습니다.",
  },
  {
    id: "24",
    slug: "bloom-as-you-are",
    title: "있는 그대로 피어나다 (Bloom As You Are)",
    year: 2025,
    medium: "화선지에 먹 (Ink on Mulberry Paper)",
    dimensions: "100 x 70 cm",
    aspectRatio: "10/7",
    description: "자신만의 방식으로 피어나는 꽃처럼, 각자의 고유한 아름다움을 표현한 작품입니다.",
    imageUrl: "/Images/Artworks/2025/heelang-bloom-as-you-are-2025.jpg",
    imageUrlQuery: "bloom authentic self calligraphy",
    artistNote: "억지로 만들어진 아름다움이 아닌, 자연스러운 본질의 아름다움을 추구했습니다.",
  },
  {
    id: "23",
    slug: "a-boy",
    title: "소년 (A Boy)",
    year: 2025,
    medium: "화선지에 먹 (Ink on Mulberry Paper)",
    dimensions: "50 x 70 cm",
    aspectRatio: "5/7",
    description: "순수함과 호기심으로 가득한 소년의 마음을 담은 작품입니다.",
    imageUrl: "/Images/Artworks/2025/heelang-a-boy-2025.jpg",
    imageUrlQuery: "boy innocence youth calligraphy",
    artistNote: "잃어버린 순수함에 대한 그리움을 서예로 표현했습니다.",
  },
  {
    id: "22",
    slug: "fortune",
    title: "복 (Fortune)",
    year: 2025,
    medium: "화선지에 먹 (Ink on Mulberry Paper)",
    dimensions: "90 x 90 cm",
    aspectRatio: "1/1",
    description: "진정한 복이 무엇인지에 대한 성찰을 담은 작품입니다.",
    imageUrl: "/Images/Artworks/2025/heelang-fortune-2025.jpg",
    imageUrlQuery: "fortune blessing happiness calligraphy",
    artistNote: "물질적 풍요보다는 마음의 평안함에서 오는 복을 표현하고자 했습니다.",
  },
  {
    id: "21",
    slug: "way",
    title: "길 (Way)",
    year: 2025,
    medium: "화선지에 먹 (Ink on Mulberry Paper)",
    dimensions: "140 x 70 cm",
    aspectRatio: "2/1",
    description: "인생의 길, 예술의 길에 대한 깊은 사유를 담은 작품입니다.",
    imageUrl: "/Images/Artworks/2025/heelang-way-2025.jpg",
    imageUrlQuery: "way path life journey calligraphy",
    artistNote: "올바른 길에 대한 끊임없는 탐구와 성찰의 과정을 표현했습니다.",
  },

  // 2024년 작품
  {
    id: "20",
    slug: "celebration",
    title: "축하 (Celebration)",
    year: 2024,
    medium: "화선지에 먹 (Ink on Mulberry Paper)",
    dimensions: "70 x 100 cm",
    aspectRatio: "7/10",
    description: "삶의 소중한 순간들을 축하하는 마음을 담은 작품입니다.",
    imageUrl: "/Images/Artworks/2024/heelang-celebration-2024.jpg",
    imageUrlQuery: "celebration joy life moments calligraphy",
    artistNote: "일상의 작은 기쁨들도 충분히 축하받을 만한 가치가 있다는 생각을 담았습니다.",
  },
  {
    id: "19",
    slug: "one-day-one-good-day",
    title: "하루 한 번 좋은 날 (One Day One Good Day)",
    year: 2024,
    medium: "화선지에 먹 (Ink on Mulberry Paper)",
    dimensions: "50 x 70 cm",
    aspectRatio: "5/7",
    description: "매일을 좋은 날로 만들어가는 긍정적인 마음가짐을 표현한 작품입니다.",
    imageUrl: "/Images/Artworks/2024/heelang-one-day-one-good-day-2024.jpg",
    imageUrlQuery: "good day positive mindset daily life calligraphy",
    artistNote: "하루하루를 감사한 마음으로 살아가는 삶의 태도를 담았습니다.",
  },
  {
    id: "18",
    slug: "ups-and-downs",
    title: "기복 (Ups and Downs)",
    year: 2024,
    medium: "화선지에 먹 (Ink on Mulberry Paper)",
    dimensions: "70 x 140 cm",
    aspectRatio: "1/2",
    description: "인생의 기복과 변화를 담담히 받아들이는 마음을 표현한 작품입니다.",
    imageUrl: "/Images/Artworks/2024/heelang-ups-and-downs-2024.jpg",
    imageUrlQuery: "ups downs life changes acceptance calligraphy",
    artistNote: "인생의 오르막과 내리막을 모두 받아들이는 평정심을 표현했습니다.",
  },
  {
    id: "17",
    slug: "truth-within-the-ordinary",
    title: "평범함 속의 진리 (Truth Within the Ordinary)",
    year: 2024,
    medium: "화선지에 먹 (Ink on Mulberry Paper)",
    dimensions: "100 x 70 cm",
    aspectRatio: "10/7",
    description: "일상의 평범한 순간들 속에서 발견되는 깊은 진리를 담은 작품입니다.",
    imageUrl: "/Images/Artworks/2024/heelang-tuth-within-the-ordinary-2024.jpg",
    imageUrlQuery: "truth ordinary daily life wisdom calligraphy",
    artistNote: "특별함을 찾기보다는 평범함 속에 숨어있는 진리에 주목했습니다.",
  },
  {
    id: "16",
    slug: "whisper-of-nature",
    title: "자연의 속삭임 (Whisper of Nature)",
    year: 2024,
    medium: "화선지에 먹 (Ink on Mulberry Paper)",
    dimensions: "90 x 90 cm",
    aspectRatio: "1/1",
    description: "자연이 들려주는 미세한 소리와 움직임을 서예로 표현한 작품입니다.",
    imageUrl: "/Images/Artworks/2024/heelang-whisper-of-nature-2024.jpg",
    imageUrlQuery: "nature whisper natural sounds calligraphy",
    artistNote: "자연과의 교감 속에서 느끼는 평온함과 경이로움을 담았습니다.",
  },
  {
    id: "15",
    slug: "stem",
    title: "줄기 (Stem)",
    year: 2024,
    medium: "화선지에 먹 (Ink on Mulberry Paper)",
    dimensions: "140 x 70 cm",
    aspectRatio: "2/1",
    description: "식물의 줄기처럼 곧게 뻗어나가는 의지와 성장을 표현한 작품입니다.",
    imageUrl: "/Images/Artworks/2024/heelang-stem-2024.jpg",
    imageUrlQuery: "stem plant growth strength calligraphy",
    artistNote: "굽히지 않는 의지와 끊임없는 성장의 의미를 줄기의 형상에 담았습니다.",
  },

  // 2023년 작품
  {
    id: "14",
    slug: "breath",
    title: "호흡 (Breath)",
    year: 2023,
    medium: "화선지에 먹 (Ink on Mulberry Paper)",
    dimensions: "70 x 100 cm",
    aspectRatio: "7/10",
    description: "생명의 가장 기본이 되는 호흡의 리듬과 흐름을 표현한 작품입니다.",
    imageUrl: "/Images/Artworks/2023/heelang-breath-2023.jpg",
    imageUrlQuery: "breath life rhythm flow calligraphy",
    artistNote: "호흡의 들숨과 날숨처럼 반복되는 생명의 리듬을 서예로 표현했습니다.",
  },
  {
    id: "13",
    slug: "inkstone",
    title: "벼루 (Inkstone)",
    year: 2023,
    medium: "화선지에 먹 (Ink on Mulberry Paper)",
    dimensions: "50 x 70 cm",
    aspectRatio: "5/7",
    description: "서예가의 가장 소중한 도구인 벼루에 대한 경외심을 담은 작품입니다.",
    imageUrl: "/Images/Artworks/2023/heelang-inkstone-2023.jpg",
    imageUrlQuery: "inkstone calligraphy tool tradition respect calligraphy",
    artistNote: "천년을 함께하는 벼루에 대한 깊은 애정과 존경을 표현했습니다.",
  },
  {
    id: "12",
    slug: "memories",
    title: "기억 (Memories)",
    year: 2023,
    medium: "화선지에 먹 (Ink on Mulberry Paper)",
    dimensions: "90 x 90 cm",
    aspectRatio: "1/1",
    description: "소중했던 기억들이 마음 속에 남긴 흔적들을 담은 작품입니다.",
    imageUrl: "/Images/Artworks/2023/heelang-memories-2023.jpg",
    imageUrlQuery: "memories past emotional traces calligraphy",
    artistNote: "시간이 지나도 변하지 않는 소중한 기억들의 가치를 표현했습니다.",
  },

  // 2022년 작품 (보물 시리즈)
  {
    id: "11",
    slug: "treasure-8",
    title: "보물 8 (Treasure 8)",
    year: 2022,
    medium: "화선지에 먹 (Ink on Mulberry Paper)",
    dimensions: "70 x 70 cm",
    aspectRatio: "1/1",
    description: "보물 시리즈의 여덟 번째 작품으로, 내면의 보물에 대한 탐구를 담았습니다.",
    imageUrl: "/Images/Artworks/2022/heelang-treasure-8-2022.jpg",
    imageUrlQuery: "treasure 8 inner wealth calligraphy",
    artistNote: "진정한 보물은 마음 속에 있다는 깨달음을 표현했습니다.",
  },
  {
    id: "10",
    slug: "treasure-7",
    title: "보물 7 (Treasure 7)",
    year: 2022,
    medium: "화선지에 먹 (Ink on Mulberry Paper)",
    dimensions: "70 x 70 cm",
    aspectRatio: "1/1",
    description: "보물 시리즈의 일곱 번째 작품으로, 지혜의 가치를 탐구합니다.",
    imageUrl: "/Images/Artworks/2022/heelang-treasure-7-2022.jpg",
    imageUrlQuery: "treasure 7 wisdom value calligraphy",
    artistNote: "물질적 가치를 넘어선 정신적 보물의 의미를 담았습니다.",
  },
  {
    id: "9",
    slug: "treasure-6",
    title: "보물 6 (Treasure 6)",
    year: 2022,
    medium: "화선지에 먹 (Ink on Mulberry Paper)",
    dimensions: "70 x 70 cm",
    aspectRatio: "1/1",
    description: "보물 시리즈의 여섯 번째 작품으로, 인간관계의 소중함을 표현합니다.",
    imageUrl: "/Images/Artworks/2022/heelang-treasure-6-2022.jpg",
    imageUrlQuery: "treasure 6 relationships human connection calligraphy",
    artistNote: "사람과 사람 사이의 진실한 연결이 가장 큰 보물임을 깨달았습니다.",
  },
  {
    id: "8",
    slug: "treasure-5",
    title: "보물 5 (Treasure 5)",
    year: 2022,
    medium: "화선지에 먹 (Ink on Mulberry Paper)",
    dimensions: "70 x 70 cm",
    aspectRatio: "1/1",
    description: "보물 시리즈의 다섯 번째 작품으로, 시간의 소중함을 다룹니다.",
    imageUrl: "/Images/Artworks/2022/heelang-treasure-5-2022.jpg",
    imageUrlQuery: "treasure 5 time precious moments calligraphy",
    artistNote: "지나간 시간은 다시 돌아오지 않는 진정한 보물입니다.",
  },
  {
    id: "7",
    slug: "treasure-4",
    title: "보물 4 (Treasure 4)",
    year: 2022,
    medium: "화선지에 먹 (Ink on Mulberry Paper)",
    dimensions: "70 x 70 cm",
    aspectRatio: "1/1",
    description: "보물 시리즈의 네 번째 작품으로, 건강한 몸과 마음의 가치를 탐구합니다.",
    imageUrl: "/Images/Artworks/2022/heelang-treasure-4-2022.jpg",
    imageUrlQuery: "treasure 4 health body mind wellness calligraphy",
    artistNote: "건강한 몸과 마음이야말로 모든 행복의 기초가 되는 보물입니다.",
  },
  {
    id: "6",
    slug: "treasure-3",
    title: "보물 3 (Treasure 3)",
    year: 2022,
    medium: "화선지에 먹 (Ink on Mulberry Paper)",
    dimensions: "70 x 70 cm",
    aspectRatio: "1/1",
    description: "보물 시리즈의 세 번째 작품으로, 사랑의 의미를 탐구합니다.",
    imageUrl: "/Images/Artworks/2022/heelang-treasure-3-2022.jpg",
    imageUrlQuery: "treasure 3 love affection heart calligraphy",
    artistNote: "진실한 사랑은 주고받을수록 더 커지는 신비로운 보물입니다.",
  },
  {
    id: "5",
    slug: "treasure-2",
    title: "보물 2 (Treasure 2)",
    year: 2022,
    medium: "화선지에 먹 (Ink on Mulberry Paper)",
    dimensions: "70 x 70 cm",
    aspectRatio: "1/1",
    description: "보물 시리즈의 두 번째 작품으로, 평화로운 마음의 가치를 표현합니다.",
    imageUrl: "/Images/Artworks/2022/heelang-treasure-2-2022.jpg",
    imageUrlQuery: "treasure 2 peace tranquility mind calligraphy",
    artistNote: "어떤 외적 조건보다도 내면의 평화가 진정한 부라는 것을 표현했습니다.",
  },
  {
    id: "4",
    slug: "treasure-1",
    title: "보물 1 (Treasure 1)",
    year: 2022,
    medium: "화선지에 먹 (Ink on Mulberry Paper)",
    dimensions: "70 x 70 cm",
    aspectRatio: "1/1",
    description: "보물 시리즈의 첫 번째 작품으로, 감사하는 마음의 소중함을 담았습니다.",
    imageUrl: "/Images/Artworks/2022/heelang-treasure-1-2022.jpg",
    imageUrlQuery: "treasure 1 gratitude appreciation heart calligraphy",
    artistNote: "모든 것에 감사할 수 있는 마음이야말로 가장 큰 보물이라는 깨달음을 담았습니다.",
  },

  // 2021년 작품
  {
    id: "3",
    slug: "black-and-white",
    title: "흑백 (Black and White)",
    year: 2021,
    medium: "화선지에 먹 (Ink on Mulberry Paper)",
    dimensions: "70 x 100 cm",
    aspectRatio: "7/10",
    description: "흑과 백의 대비를 통해 삶의 이중성과 조화를 표현한 작품입니다.",
    imageUrl: "/Images/Artworks/2021/heelang-black-and-white-2021.jpg",
    imageUrlQuery: "black white contrast duality life calligraphy",
    artistNote: "상반된 것들이 만나 이루는 완전한 조화의 아름다움을 추구했습니다.",
  },
  {
    id: "2",
    slug: "echo",
    title: "메아리 (Echo)",
    year: 2021,
    medium: "화선지에 먹 (Ink on Mulberry Paper)",
    dimensions: "90 x 90 cm",
    aspectRatio: "1/1",
    description: "마음의 소리가 울려 퍼지는 메아리의 감동을 담은 작품입니다.",
    imageUrl: "/Images/Artworks/2021/heelang-echo-2021.jpg",
    imageUrlQuery: "echo sound reverberation heart emotion calligraphy",
    artistNote: "내면의 목소리가 세상과 공명하며 만들어내는 아름다운 울림을 표현했습니다.",
  },
  {
    id: "1",
    slug: "hologram",
    title: "홀로그램 (Hologram)",
    year: 2021,
    medium: "화선지에 먹 (Ink on Mulberry Paper)",
    dimensions: "70 x 100 cm",
    aspectRatio: "7/10",
    description: "다차원적 현실과 환상의 경계를 탐구한 실험적 작품입니다.",
    imageUrl: "/Images/Artworks/2021/heelang-hologram-2021.jpg",
    imageUrlQuery: "hologram dimension reality illusion modern calligraphy",
    artistNote: "전통 서예와 현대적 감각의 만남을 통해 새로운 차원의 작품을 시도했습니다.",
  },
]
